project_id = "sfuetbkoxsbqvpkdfxsf"

[functions.chat]
verify_jwt = false

[functions.web-search]
verify_jwt = false

[functions.get-news]
verify_jwt = false

[functions.google-tts]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
